# Generated by Django 3.2.6 on 2021-10-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones_Ahorros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identidad', models.CharField(max_length=15)),
                ('Fecha', models.DateField()),
                ('Num_Recibo', models.IntegerField()),
                ('Deposito', models.FloatField()),
                ('Intereses', models.FloatField()),
                ('Retiro', models.FloatField()),
                ('Saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Ahorros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identidad', models.CharField(max_length=15)),
                ('Nombre', models.CharField(max_length=50)),
                ('Beneficiarios', models.CharField(max_length=100)),
                ('Observacions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Datos_Acciones_Ahorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identidad', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=15)),
                ('Fecha', models.DateField()),
                ('Num_Recibo', models.IntegerField()),
                ('Deposito', models.FloatField()),
                ('Intereses', models.FloatField()),
                ('Retiro', models.FloatField()),
                ('Saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Datos_Ahorrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=15)),
                ('Identidad', models.CharField(max_length=15)),
                ('Nombre', models.CharField(max_length=50)),
                ('Beneficiarios', models.CharField(max_length=100)),
                ('Observacions', models.CharField(max_length=100)),
            ],
        ),
    ]
