# Generated by Django 3.2.6 on 2021-10-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_datos_acciones_ahorro',
            name='usuario',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='temp_datos_ahorrante',
            name='usuario',
            field=models.CharField(max_length=30),
        ),
    ]
