# Generated by Django 3.2.6 on 2021-10-13 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Num_Recibo', models.IntegerField()),
                ('Descripción', models.CharField(max_length=50)),
                ('Entrada', models.FloatField()),
                ('Salida', models.FloatField()),
                ('Saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=15)),
                ('Fecha', models.DateField(default=datetime.datetime(2021, 10, 13, 20, 24, 1, 835817, tzinfo=utc))),
                ('Num_Recibo', models.IntegerField()),
                ('Descripción', models.CharField(max_length=50)),
                ('Entrada', models.FloatField()),
                ('Salida', models.FloatField()),
                ('Saldo', models.FloatField()),
            ],
        ),
    ]
